function init(self)
	msg.post(".", "acquire_input_focus")
	local node = gui.get_node("restart")
	gui.animate(node, "scale", vmath.vector3(1.2,1.2,1), gui.EASING_INSINE, 1.5, 0, function() end, gui.PLAYBACK_LOOP_PINGPONG)
end

function on_input(self, action_id, action)
	if action_id == hash("jump") and action.pressed then
		msg.post("main:/loader#loader", "unload_level", { proxy = "#proxy_game_over" })
		msg.post("main:/loader#loader", "load_level")
	end
end
